openapi: 3.0.3
info:
  description: This is an OpenAPI definition file which contains violations of the rule 'A verb or verb phrase should be used for controller names' created by experts.
  version: 0.1.0
  title: Example OpenAPI Definition File
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.example.com/v1
    description: Production server (uses live data)
  - url: https://sandbox-api.example.com:8443/v1
    description: Sandbox server (uses test data)
paths:
  # Justus (+1 violation)
  /departments/human-resources/employees:
    get:
      tags:
        - employees management
      description: Returns a list of employees
      summary: Return list employees
      responses:
        200:
          description: Employees object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employees"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Justus (+1 violation)
  /animals/geese/species:
    get:
      tags:
        - species management
      description: Returns species of geese
      summary: Return geese species
      responses:
        200:
          description: Species object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Species"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Sebastian (+1 violation)
  /products/trousers:
    get:
      tags:
        - trousers management
      description: Returns trousers
      summary: Return trousers
      responses:
        200:
          description: Trousers object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trousers"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Sebastian (+1 violation)
  /products/information-items:
    get:
      tags:
        - information of items management
      description: Returns information about items
      summary: Return information items
      responses:
        200:
          description: Information object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Information"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Ana Franco Da Silva  (+1 violation)
  /items/shirts:
    get:
      tags:
        - shirts items
      description: Returns shirts
      summary: Return shirts
      responses:
        200:
          description: Shirt list object
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Shirt"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Ana Franco Da Silva (+1 violation)
  /items/jeans:
    get:
      tags:
        - Jeans items
      description: Returns a jeans
      summary: Get jeans
      responses:
        200:
          description: Jeans list object
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Jeans"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Ana Franco Da Silva (+1 violation)
  /items/leggings:
    get:
      tags:
        - Leggings items
      description: Returns a eggings object
      summary: Get leggings
      responses:
        200:
          description: Leggings list object
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Leggings"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Oliver (+1 violation)
  /my-cases/top-priority-cases/details:
    get:
      tags:
        - Details-case items
      description: Returns details about a case
      summary: Get details case
      responses:
        200:
          description: Details list object
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Details"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Pfaff (+1 violation)
  /databases/{databaseId}/admins:
    get:
      tags:
        - Admin items
      description: Returns list of admins
      summary: Get the admin of a specific database
      parameters:
        - name: databaseId
          in: path
          required: true
          description: The ID of the database
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Admin object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Admin"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
components:
  schemas:
    Species:
      description: A species of an animal
      type: object
      properties:
        speciesId:
          type: number
        speciesName:
          type: string
        speciesDescription:
          type: string
    Employees:
      description: List of employees
      type: object
      properties:
        employeesIds:
          type: integer
        count:
          type: integer
    Information:
      description: List of informations
      type: object
      properties:
        informationIds:
          type: integer
        count:
          type: integer
    Trousers:
      description: List of trousers
      type: object
      properties:
        trousersIds:
          type: integer
        count:
          type: integer
    Shirt:
      description: Shirt object
      type: object
      properties:
        shirtIds:
          type: integer
        size:
          type: string
    Jeans:
      description: Jeans object
      type: object
      properties:
        jeansIds:
          type: integer
        size:
          type: string
    Leggings:
      description: Leggings object
      type: object
      properties:
        legginsIds:
          type: integer
        size:
          type: string
    Admin:
      description: Admin object
      type: object
      properties:
        adminIds:
          type: integer
        adminName:
          type: string
    Details:
      description: Details object
      type: object
      properties:
        detailsIds:
          type: integer
        detailsName:
          type: string
    GenericResponse:
      description: A generic response object with a message attribute
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
security:
  - BasicAuth: []
