openapi: 3.0.3
info:
  description: This is an OpenAPI definition file which contains violations of the rule 'A verb or verb phrase should be used for controller names' created by experts.
  version: 0.1.0
  title: Example OpenAPI Definition File
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.example.com/v1
    description: Production server (uses live data)
  - url: https://sandbox-api.example.com:8443/v1
    description: Sandbox server (uses test data)
paths:
  # Ana Franco Da Silva (+1 violation)
  /users/1/present:
    put:
      tags:
        - presence
      description: Check the presence of a user
      summary: Check presence
      responses:
        200:
          description: Successfully checked presence
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Ana Franco Da Silva (+1 violation)
  /users/1/permit:
    put:
      tags:
        - permission
      description: Permit a user
      summary: Permit a user
      responses:
        200:
          description: Successfully permit a user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # RULE 14: A verb or verb phrase should be used for controller (+1 violation)
  /animals/{catId}/foods/{foodId}/deliver-food:
    put:
      tags:
        - food delivery
      description: Deliver food to cat
      summary: Deliver food to cat
      parameters:
        - in: path
          name: catId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The cat id
        - in: path
          name: foodId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The food id
      responses:
        200:
          description: Successfully delivered food to cat
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # RULE 14: A verb or verb phrase should be used for controller (+1 violation)
  /animals/{catId}/foods/{foodId}/remove-food:
    delete:
      tags:
        - food removal
      description: Remove a food from a cat
      summary: Remove food
      parameters:
        - in: path
          name: catId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The cat id
        - in: path
          name: foodId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The food id
      responses:
        200:
          description: Successfully removed food from a cat
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
components:
  schemas:
    GenericResponse:
      description: A generic response object with a message attribute
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
security:
  - BasicAuth: []
