openapi: 3.0.3
info:
  description: This is an OpenAPI definition file which contains violations of the rule 'Underscores (_) should not be used in URIs' created by experts.
  version: 0.1.0
  title: Example OpenAPI Definition File
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.example.com/v1
    description: Production server (uses live data)
  - url: https://sandbox-api.example.com:8443/v1
    description: Sandbox server (uses test data)
paths:
  # Justus (+1 violation)
  /retrieve-order/{id}:
    get:
      tags:
        - order management
      description: Returns an order
      summary: Return order
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the customer
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Order object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Justus + Ana Franco da Silva (+1 violation)
  /get-order/{id}:
    get:
      tags:
        - order management
      description: Returns an order
      summary: Return order
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the customer
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Order object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Justus (+1 violation)
  /fetch-orders:
    get:
      tags:
        - order management
      description: Returns an order
      summary: Return order
      responses:
        200:
          description: Order object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Justus + Ana Franco da Silva (+1 violation)
  /delete-order/{id}:
    delete:
      tags:
        - order management
      description: Deletes a specific order identified via ID
      summary: Delete a specific order
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user who should be deleted
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Successfully deleted user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Sebastian (+1 violation)
  /add-user:
    post:
      tags:
        - user management
      description: Creates an user
      summary: Create an user
      requestBody:
        description: An user object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:
          description: Successfully created an user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Sebastian (+1 violation)
  /delete-user:
    delete:
      tags:
        - user management
      description: Deletes an user
      summary: Delete an user
      responses:
        200:
          description: Successfully deleted user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Sebastian (+1 violation)
  /{id}/fetch:
    get:
      tags:
        - order management
      description: Returns an specific order identified via ID
      summary: Return specific order
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Order object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Lukas Mohs (+1 violation)
  /orders/get-all:
    get:
      tags:
        - order management
      description: Returns a list of orders
      summary: Returns list of orders
      responses:
        200:
          description: Array of order objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Oliver Kopp (+1 violation)
  /users/{id}/names/delete:
    delete:
      tags:
        - user management
      description: Deletes names of an user identified via ID
      summary: Delete names of an user
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user who should be deleted
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Successfully deleted user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Timo Pfaff (+1 violation)
  /queues/{queueId}/messages/purge-queue:
    delete:
      tags:
        - queue management
      description: Delete all messages in a queue identified via ID
      summary: Delete all messages in a queue
      parameters:
        - name: queueId
          in: path
          required: true
          description: The ID of the queue
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Successfully deleted messages in queue
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Maik Betka (+1 violation)
  /users/create:
    post:
      tags:
        - user management
      description: Creates an user
      summary: Create an user
      requestBody:
        description: An user object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:
          description: Successfully created an user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Maik Betka (+1 violation)
  /create-user/{id}:
    post:
      tags:
        - user management
      description: Creates an user
      summary: Create an user
      requestBody:
        description: An user object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Successfully created an user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Maik Betka (+1 violation)
  /users/put:
    put:
      tags:
        - user management
      description: Updates the details of an user
      summary: Update an user
      requestBody:
        description: User object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:
          description: Successful request
          content:
            text/plain:
              schema:
                type: string
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
components:
  schemas:
    User:
      description: A user of the system
      type: object
      properties:
        userId:
          type: number
        userName:
          type: string
        email:
          type: string
    Order:
      description: A order from a customer
      type: object
      properties:
        articleNumber:
          type: integer
        count:
          type: integer
        price:
          type: number
    GenericResponse:
      description: A generic response object with a message attribute
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
security:
  - BasicAuth: []
