openapi: 3.0.3
info:
  description: This is an OpenAPI definition file which contains violations of the rule 'Underscores (_) should not be used in URIs' created by experts.
  version: 0.1.0
  title: Example OpenAPI Definition File
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.example.com/v1
    description: Production server (uses live data)
  - url: https://sandbox-api.example.com:8443/v1
    description: Sandbox server (uses test data)
paths:
  # Justus + Lukas Mohs (+1 violation)
  /customers/{id}/orders.xml:
    get:
      tags:
        - customers management
      description: Returns an order
      summary: Return order
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the customer
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Order object
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Order"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Justus + Sebastian + Ana Franco da Silva (+1 violation)
  /customers/{id}/orders.json:
    get:
      tags:
        - customers management
      description: Returns an order
      summary: Return order
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the customer
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Order object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Justus + Sebastian (+1 violation)
  /customers/{id}/orders.html:
    get:
      tags:
        - customers management
      description: Returns an order
      summary: Return order
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the customer
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Order object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Justus (+1 violation)
  /customers/{id}/orders.pdf:
    get:
      tags:
        - customers management
      description: Returns an order
      summary: Return order
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the customer
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Order object
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Sebastian (+1 violation)
  /customers/{id}/orders/json:
    get:
      tags:
        - customers management
      description: Returns an order
      summary: Return order
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the customer
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Order object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Sebastian (+1 violation)
  /customers/{id}/orders/html:
    get:
      tags:
        - customers management
      description: Returns an order
      summary: Return order
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the customer
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Order object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Timo Pfaff (+1 violation)
  /customers/{id}/orders.pdf/download:
    get:
      tags:
        - customers management
      description: Returns an order
      summary: Return order
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the customer
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Order object
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Oliver Kopp (+1 violation)
  /customers/{id}/orders.heic:
    get:
      tags:
        - customers management
      description: Returns an order
      summary: Return order
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the customer
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Order object
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
components:
  schemas:
    Order:
      description: A order from a customer
      type: object
      properties:
        articleNumber:
          type: integer
        count:
          type: integer
        price:
          type: number
    GenericResponse:
      description: A generic response object with a message attribute
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
security:
  - BasicAuth: []
