openapi: 3.0.3
info:
  description: This is an OpenAPI definition file which contains violations of the rule 'Underscores (_) should not be used in URIs' created by experts.
  version: 0.1.0
  title: Example OpenAPI Definition File
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.example.com/v1
    description: Production server (uses live data)
  - url: https://sandbox-api.example.com:8443/v1
    description: Sandbox server (uses test data)
paths:
  # Justus (+1 violation)
  /videogames/{id}:
    get:
      tags:
        - video games
      description: Returns an video game identified via ID
      summary: Return video game
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the videeo game
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Video game object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VideoGame"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Justus (+1 violation)
  /weatherstations:
    get:
      tags:
        - weather stations
      description: Returns a list of weather stations
      summary: Return weather stations
      responses:
        200:
          description: Weather station object
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WeatherStation"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Justus (+1 violation)
  /databaseservers/{id}:
    delete:
      tags:
        - database server
      description: Deletes a database server identified via ID
      summary: Delete database server
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the database server
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Successfully deleted database server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Sebastian (+1 violation)
  /users/{userId}/contactdetails:
    get:
      tags:
        - user management
      description: Returns the contact details of a user of a system identified via ID
      summary: Return contact details
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: User object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Sebastian (+1 violation)
  /users/johndoe:
    delete:
      tags:
        - user management
      description: Delete user john doe
      summary: Delete user
      responses:
        200:
          description: Successfully deleted user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Ana Franco da Silva (+1 violation)
  /users/1/myissues/13:
    get:
      tags:
        - user management
      description: Returns issue 13 from user 1
      summary: Return issue
      responses:
        200:
          description: Issue object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Issue"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Oliver Kopp (+1 violation)
  /premiumusers/{userId}:
    get:
      tags:
        - user management
      description: Returns premium user identified via ID
      summary: Return user
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: User object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Timo Pfaff (+1 violation)
  /university+of+stuttgart/students/{studentId}:
    delete:
      tags:
        - student management
      description: Deletes student of the University of Stuttgart identified via ID
      summary: Delete student
      parameters:
        - name: studentId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Successfully deleted student
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Maik Betka (+1 violation)
  /blogs/firstnamesurname/mytitles:
    delete:
      tags:
        - blog
      description: Deletes titles from a blog from a user
      summary: Delete titles
      responses:
        200:
          description: Successfully deleted titles
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
components:
  schemas:
    User:
      description: A user of the system
      type: object
      properties:
        userId:
          type: number
        userName:
          type: string
        email:
          type: string
    Issue:
      description: A issue from a user
      type: object
      properties:
        number:
          type: integer
        title:
          type: string
        comment:
          type: string
    VideoGame:
      description: A video game
      type: object
      properties:
        articleNumber:
          type: integer
        name:
          type: string
        price:
          type: number
    WeatherStation:
      description: A weather station
      type: object
      properties:
        location:
          type: string
        name:
          type: string
    DatabaseServer:
      description: A database server
      type: object
      properties:
        location:
          type: string
        ip:
          type: string
    GenericResponse:
      description: A generic response object with a message attribute
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
security:
  - BasicAuth: []
