openapi: 3.0.3
info:
  description: This is an OpenAPI definition file which contains violations of the rule '401 (Unauthorized) must be used when there is a problem with the client credentials' created by experts.
  version: 0.1.0
  title: Example OpenAPI Definition File
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.example.com/v1
    description: Production server (uses live data)
  - url: https://sandbox-api.example.com:8443/v1
    description: Sandbox server (uses test data)
paths:
  # Justus (+1 violation)
  /users:
    get:
      tags:
        - user management
      description: Returns a list of all users
      summary: Get all users
      responses:
        200:
          description: Array of user objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Sebastian (+3 violations) + Timo Pfaff for put operation + Maik Betka for delete
  /users/{userId}:
    get:
      tags:
        - user management
      description: Returns the details of a user identified via ID
      summary: Get a specific user
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: User object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        403:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
    put:
      tags:
        - user management
      description: Updates the details of a specific user identified via ID
      summary: Update a specific user
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            minimum: 1
      requestBody:
        description: User object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:
          description: Successful request
          content:
            text/plain:
              schema:
                type: string
        400:
          description: Client error including problems with client credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
    delete:
      tags:
        - user management
      description: Deletes a specific user identified via ID
      summary: Delete a specific user
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user who should be deleted
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Successfully deleted user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        500:
          description: Error, including problems with client credentials 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Lukas Mohs + Sebastiona (+1 violation)
  /users/{userId}/mails:
    post:
      tags:
        - user management
      description: Creates e-mail address of a user that is identified by an ID
      summary: Create mail address
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            minimum: 1
      requestBody:
        description: A mail object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Mail"
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
        401:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        403:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Ana Franco da Silva (+1 violation)
  /users/{userId}/locations:
    post:
      tags:
        - user management
      description: Creates location of a user that is identified by an ID
      summary: Create location
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            minimum: 1
      requestBody:
        description: A location object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Location"
      responses:
        200:
          description: Location object
          content:
            text/plain:
              schema:
                type: string
        404:
          description: Not found, including problems with client credentials 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
components:
  schemas:
    User:
      description: A user of the system
      type: object
      properties:
        userId:
          type: number
        userName:
          type: string
        email:
          type: string
    Mail:
      description: A mail address from a user
      type: object
      properties:
        userId:
          type: number
        address:
          type: string
        primary:
          type: boolean 
    Location:
      description: A location from a user
      type: object
      properties:
        userId:
          type: number
        street:
          type: string
        houseNumber:
          type: integer 
        postalCode:
          type: integer
    GenericResponse:
      description: A generic response object with a message attribute
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
security:
  - BasicAuth: []
